Practice 6

6. Change k from 5 to 3 in notebook 3's toy example and recompute the vote by hand. Does the prediction change?

Cell 1

In [1]:
# Always import required libraries before using them.

import numpy as np
import pandas as pd

Cell 2

In [2]:
# Training data contains features and labels.

X_toy = np.array([
    [1.0, 2.0],
    [1.5, 1.8],
    [1.2, 2.6],
    [2.0, 2.2],
    [0.8, 1.5],
    [4.5, 4.0],
    [5.0, 3.5],
    [4.2, 4.8],
    [5.5, 4.2],
    [4.8, 3.2]])

y_toy = np.array([0,0,0,0,0,1,1,1,1,1])

query = np.array([3.0, 3.0])

Cell 3

In [3]:
# Euclidean distance measures how far two points are from each other.

distances = np.sqrt(((X_toy - query) ** 2).sum(axis=1))

Cell 4

In [4]:
# Sort distances from smallest to largest.

order = np.argsort(distances)

Cell 5

In [5]:
# Nearest neighbors are determined by distance.

neighbors = pd.DataFrame({"point": [tuple(p) for p in X_toy[order]],
"class": y_toy[order],"distance": distances[order].round(2)})

print(neighbors)

        point  class  distance
0  (2.0, 2.2)      0      1.28
1  (4.5, 4.0)      1      1.80
2  (4.8, 3.2)      1      1.81
3  (1.2, 2.6)      0      1.84
4  (1.5, 1.8)      0      1.92
5  (5.0, 3.5)      1      2.06
6  (4.2, 4.8)      1      2.16
7  (1.0, 2.0)      0      2.24
8  (0.8, 1.5)      0      2.66
9  (5.5, 4.2)      1      2.77


Cell 6

In [6]:
# k is the number of neighbors used for voting.

k = 3

Cell 7

In [7]:
# Choose the labels of the k nearest neighbors.

nearest_k_labels = y_toy[order[:k]]

nearest_k_labels

array([0, 1, 1])

Cell 8

In [8]:
# Only the nearest k neighbors participate in voting.

print(nearest_k_labels)

[0 1 1]


Cell 9

In [9]:
# Count how many votes each class receives.

votes = np.bincount(nearest_k_labels)

votes

array([1, 2])

Cell 10

In [10]:
# The class with the most votes becomes the prediction.

prediction = np.argmax(votes)

prediction

np.int64(1)

Cell 11

In [11]:
# Majority vote decides the final class.

print("Votes:", votes)
print("Prediction:", prediction)

Votes: [1 2]
Prediction: 1


Cell 12

In [12]:
# Compare old and new predictions after changing k.

old_prediction = 0
new_prediction = prediction

Cell 13

In [13]:
# Changing k can change the result.

print("Prediction with k=5 :", old_prediction)
print("Prediction with k=3 :", new_prediction)

Prediction with k=5 : 0
Prediction with k=3 : 1


Cell 14

In [14]:
# Different neighbors can lead to different decisions.

if old_prediction == new_prediction:
    print("Prediction did not change")
else:
    print("Prediction changed")

Prediction changed
