In [1]:

import numpy as np

arr = np.random.randint(0,101,(5,5))

print("Before:")
print(arr)

arr[arr > 50] = 0

print("After:")
print(arr)


Before:
[[15  5 52 43  3]
 [86 28  6  2 37]
 [42 32  8 93 60]
 [31 37 94 29 85]
 [32 74 99 34 17]]
After:
[[15  5  0 43  3]
 [ 0 28  6  2 37]
 [42 32  8  0  0]
 [31 37  0 29  0]
 [32  0  0 34 17]]


In [2]:
import numpy as np

arr = np.random.randint(0,100,(10,3))
print("Orlginal")
print(arr)

min1 = arr.min(axis=0)
max2 = arr.max(axis=0)

normal = (arr - min1) / (max2 - min1)

print("Normalized:")
print(normal)


Orlginal
[[56 39 63]
 [56 13 27]
 [59  3 83]
 [92 45  0]
 [85 53 30]
 [65 53 53]
 [18 48  6]
 [76 14 65]
 [32 41 18]
 [51 94 21]]
Normalized:
[[0.51351351 0.3956044  0.75903614]
 [0.51351351 0.10989011 0.3253012 ]
 [0.55405405 0.         1.        ]
 [1.         0.46153846 0.        ]
 [0.90540541 0.54945055 0.36144578]
 [0.63513514 0.54945055 0.63855422]
 [0.         0.49450549 0.07228916]
 [0.78378378 0.12087912 0.78313253]
 [0.18918919 0.41758242 0.21686747]
 [0.44594595 1.         0.25301205]]


In [3]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

distance =np.sum((a-b)**2)

print(distance)

27


In [4]:
import numpy as np
import time

x = np.arange(1000000)

start = time.time()
result = x**2 + 2*x + 1
end = time.time()

print("Numpy Time:")
print(end-start)

start = time.time()
result = []
for i in x:
    result.append(i**2 + 2*i + 1)
end = time.time()

print("loop Time")
print(end-start)



Numpy Time:
0.014983654022216797
loop Time
0.2580227851867676


In [5]:
import numpy as np

scores = np.array([[0.1,0.7,0.2],[0.8,0.1,0.1],[0.2,0.3,0.5],[0.9,0.05,0.05],[0.1,0.2,0.7]])

true_labels = np.array([1,0,2,0,2])

predicted = np.argmax(scores,axis = 1)

accuracy = np.mean(predicted == true_labels)

print("Prediction:")
print(predicted)

print("Accuracy:")
print(accuracy)


Prediction:
[1 0 2 0 2]
Accuracy:
1.0
